name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  pull-requests: write
  pages: write
  id-token: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout le repo git
        uses: actions/checkout@v4

      - name: Installe Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Installe des dépendances
        run: npm ci

      - name: Execute les tests
        run: npm test

      - name: Lint le code
        run: npm run lint

      - name: Generate Allure Report
        if: always() && (hashFiles('allure-results/**') != '')
        run: npx allure generate -o allure-report allure-results

      - name: Upload Allure Report (artifact)
        if: always() && (hashFiles('allure-report/**') != '')
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 7

      # commentaire PR
      - name: Comment PR (status + lien)
        if: always() && github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: allure
          message: |
            **CI status:** `${{ job.status }}`
            **Run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            **Allure artifact:** `allure-report` (à télécharger depuis le run)

      # préparer l’artefact pour GitHub Pages (seulement sur master)
      - name: Upload Pages artifact
        if: always() && github.ref == 'refs/heads/master' && (hashFiles('allure-report/**') != '')
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

  deploy-pages:
    needs: ci
    if: always() && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
